# #######################################################################################
# HYPRLAND CONFIG
# #######################################################################################

# This is a modular Hyprland config file.
# Refer to the wiki for more information: https://wiki.hypr.land/Configuring/

# Modular config sources
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/colors.conf
source = $HOME/.config/hypr/decorations.conf
source = $HOME/.config/hypr/animations.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windowrules.conf

################
### MONITORS ###
################


###################
### MY PROGRAMS ###
###################

# Set programs that you use
$terminal = kitty
$fileManager = dolphin --platformtheme kde
$menu = rofi -show drun
env = QT_QPA_PLATFORMTHEME,kde


#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = bash -c 'hyprpaper & sleep 1; wp=$(find ~/Pictures/catppuccin-wallpapers -type f \( -iname "*.jpg" -o -iname "*.png" \) | shuf -n 1); hyprctl hyprpaper preload "$wp"; hyprctl hyprpaper wallpaper ",$wp"'
exec-once = ~/.config/hypr/Scripts/start_clipboard.sh


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24



###################
### PERMISSIONS ###
###################



#####################
### LOOK AND FEEL ###
#####################

# General settings
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(cba6f7ee) rgba(89b4faee) 45deg
    col.inactive_border = rgba(45475aaa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

# Dwindle layout settings
dwindle {
    preserve_split = true
}

# Master layout settings
master {
    new_status = master
}

# Miscellaneous settings
misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
    disable_splash_rendering = true
}



#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

# Per-device input config
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}



###################
### KEYBINDINGS ###
###################

# Keybindings are in keybinds.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################

# Window rules are in windowrules.conf
